import { Pool } from "pg";
import { eq } from "drizzle-orm";
import { afterAll, afterEach, beforeEach, describe, expect, it } from "vitest";

import { db } from "@/db/client";
import { migrationDatabaseUrl } from "@/config/env";
import { account, session as sessionTable, user as userTable, verification } from "@/db/schema/auth-schema";
import { UnauthorizedError, ValidationError } from "@/shared/domain/errors";
import { createVerifiedUser } from "../../../../tests/integration/fixtures";
import { resetDatabase } from "../../../../tests/integration/reset-database";

import { auth } from "./auth";
import { deleteAccountAtomically } from "./account-deletion";

/**
 * The runtime `holdria_app` role (`db`, `DATABASE_URL`) intentionally has
 * no DDL privileges (drizzle/roles.sql — least-privilege by design), so the
 * failure-injection test below needs the migration-privileged role
 * (`holdria_migrator`, `MIGRATION_DATABASE_URL`) to install and remove its
 * trigger.
 */
const ddlPool = new Pool({ connectionString: migrationDatabaseUrl() });

/**
 * PostgreSQL-backed coverage for the atomic account-deletion transaction
 * (finding: "Atomic account deletion" / tasks.md 3.6). Exercises the real
 * confirmation checks and the real transaction against Postgres, including
 * a failure-injection case proving that a mid-transaction failure leaves
 * no partially deleted state.
 */

beforeEach(async () => {
  await resetDatabase();
});

afterEach(async () => {
  // Best-effort cleanup in case a failure-injection test's trigger survives
  // an assertion failure.
  await ddlPool.query(`DROP TRIGGER IF EXISTS block_test_user_deletion ON "user"`);
  await ddlPool.query(`DROP FUNCTION IF EXISTS block_test_user_deletion()`);
});

afterAll(async () => {
  await ddlPool.end();
});

describe("deleteAccountAtomically", () => {
  it("deletes the user, its cascade-owned rows, and any pending verification rows", async () => {
    const testUser = await createVerifiedUser();

    // Leaves a pending password-reset verification row (value = user id,
    // per Better Auth's `/request-password-reset` route) that has no
    // foreign key to the user row and would not cascade.
    await auth.api.requestPasswordReset({ body: { email: testUser.email } });
    const [pendingBefore] = await db
      .select()
      .from(verification)
      .where(eq(verification.value, testUser.userId));
    expect(pendingBefore).toBeDefined();

    await deleteAccountAtomically(testUser.headers, { password: testUser.password });

    const [remainingUser] = await db.select().from(userTable).where(eq(userTable.id, testUser.userId));
    expect(remainingUser).toBeUndefined();

    const remainingSessions = await db
      .select()
      .from(sessionTable)
      .where(eq(sessionTable.userId, testUser.userId));
    expect(remainingSessions).toHaveLength(0);

    const remainingAccounts = await db.select().from(account).where(eq(account.userId, testUser.userId));
    expect(remainingAccounts).toHaveLength(0);

    const remainingVerifications = await db
      .select()
      .from(verification)
      .where(eq(verification.value, testUser.userId));
    expect(remainingVerifications).toHaveLength(0);
  });

  it("rejects deletion with an incorrect password and keeps the account fully intact", async () => {
    const testUser = await createVerifiedUser();

    await expect(
      deleteAccountAtomically(testUser.headers, { password: "not-the-real-password" }),
    ).rejects.toBeInstanceOf(ValidationError);

    const [remainingUser] = await db.select().from(userTable).where(eq(userTable.id, testUser.userId));
    expect(remainingUser).toBeDefined();
  });

  it("rejects deletion with no session", async () => {
    await expect(deleteAccountAtomically(new Headers(), { password: "irrelevant" })).rejects.toBeInstanceOf(
      UnauthorizedError,
    );
  });

  it("rolls back the entire transaction — including the verification cleanup — when the user deletion fails partway, leaving no partially deleted state", async () => {
    const testUser = await createVerifiedUser();
    await auth.api.requestPasswordReset({ body: { email: testUser.email } });

    // Failure injection: a trigger that makes deleting this specific
    // user's row fail, simulating a mid-transaction fault (constraint
    // violation, connection loss, crash) after the verification cleanup
    // has already run inside the same transaction.
    await ddlPool.query(`
      CREATE OR REPLACE FUNCTION block_test_user_deletion() RETURNS trigger AS $$
      BEGIN
        RAISE EXCEPTION 'injected failure: simulated fault deleting user row';
      END;
      $$ LANGUAGE plpgsql;
    `);
    // CREATE TRIGGER's WHEN clause is DDL and cannot take a bound
    // parameter; `testUser.userId` is a UUID generated by the fixture
    // above, not external input, so inlining it is safe here.
    await ddlPool.query(`
      CREATE TRIGGER block_test_user_deletion
      BEFORE DELETE ON "user"
      FOR EACH ROW
      WHEN (OLD.id = '${testUser.userId}'::uuid)
      EXECUTE FUNCTION block_test_user_deletion();
    `);

    await expect(
      deleteAccountAtomically(testUser.headers, { password: testUser.password }),
    ).rejects.toBeTruthy();

    // Nothing committed: the verification row this transaction also
    // deleted is back, and the user, its session, and its credential
    // account are all still present — proving the failed user-row delete
    // rolled back the whole transaction rather than leaving the
    // verification cleanup applied on its own.
    const [remainingUser] = await db.select().from(userTable).where(eq(userTable.id, testUser.userId));
    expect(remainingUser).toBeDefined();

    const remainingSessions = await db
      .select()
      .from(sessionTable)
      .where(eq(sessionTable.userId, testUser.userId));
    expect(remainingSessions.length).toBeGreaterThan(0);

    const remainingAccounts = await db.select().from(account).where(eq(account.userId, testUser.userId));
    expect(remainingAccounts.length).toBeGreaterThan(0);

    const remainingVerifications = await db
      .select()
      .from(verification)
      .where(eq(verification.value, testUser.userId));
    expect(remainingVerifications.length).toBeGreaterThan(0);

    await ddlPool.query(`DROP TRIGGER block_test_user_deletion ON "user"`);
    await ddlPool.query(`DROP FUNCTION block_test_user_deletion()`);
  });
});
